CREATE TABLE SUBCATEGORY (
  SUBCATEGORY_ID NUMBER,
  CONSTRAINT SUBCATEGORY_PK PRIMARY KEY(SUBCATEGORY_ID),
  NAME NVARCHAR2(50),
  CATEGORY_ID NUMBER,
  CONSTRAINT CATEGORY_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE SEQUENCE SUBCATEGORY_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;