CREATE TABLE USERS (
  USER_ID NUMBER,
  CONSTRAINT USER_PK PRIMARY KEY(USER_ID),
  FIRST_NAME NVARCHAR2(50),
  LAST_NAME NVARCHAR2(50),
  USERNAME NVARCHAR2(50),
  PASSWORD NVARCHAR2(50)
);

CREATE SEQUENCE USERS_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;