CREATE TABLE ANNOUNCEMENT (
  ANNOUNCEMENT_ID NUMBER,
  CONSTRAINT ANNOUNCEMENT_PK PRIMARY KEY(ANNOUNCEMENT_ID),
  TITLE NVARCHAR2(50),
  DESCRIPTION NVARCHAR2(200),
  PRICE NUMBER,
  CURRENCY NVARCHAR2(10),
  CATEGORY NVARCHAR2(20),
  SUBCATEGORY NVARCHAR2(20),
  CITY NVARCHAR2(50),
  PHONE NVARCHAR2(13),
  USER_ID NUMBER,
  CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  ESTATE_ID NUMBER,
  CONSTRAINT ESTATE_FK FOREIGN KEY(ESTATE_ID) REFERENCES ESTATE(ESTATE_ID),
  ACTIVE_FROM TIMESTAMP,
  ACTIVE_TO TIMESTAMP,
  CREATE_DATE TIMESTAMP
);

CREATE SEQUENCE ANNOUNCEMENT_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;