CREATE TABLE ANNOUNCEMENT (
  ANNOUNCEMENT_ID NUMBER,
  CONSTRAINT ANNOUNCEMENT_PK PRIMARY KEY(ANNOUNCEMENT_ID),
  TITLE NVARCHAR2(50),
  DESCRIPTION NVARCHAR2(200),
  PRICE NUMBER,
  CURRENCY NVARCHAR2(10),
  SUBCATEGORY_ID NUMBER,
  CONSTRAINT SUBCATEGORY_FK FOREIGN KEY(SUBCATEGORY_ID) REFERENCES SUBCATEGORY(SUBCATEGORY_ID),
  CITY NVARCHAR2(50),
  PHONE NVARCHAR2(13),
  USER_ID NUMBER,
  CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  ACTIVE_FROM TIMESTAMP,
  ACTIVE_TO TIMESTAMP,
  CREATE_DATE TIMESTAMP
);

CREATE SEQUENCE ANNOUNCEMENT_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;