CREATE TABLE FLIGHT_PASSENGER (
  FLIGTH_ID NUMBER,
  CONSTRAINT FLIGHT_FK FOREIGN KEY(FLIGTH_ID) REFERENCES FLIGHT(ID),
  PASSENGER_ID NUMBER,
  CONSTRAINT PASSENGER_FK FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(ID)
);