CREATE TABLE FLIGHT_PASSENGER (
  FLIGHT_PASSENGER_ID NUMBER,
  CONSTRAINT FLIGHT_PASSENGER_PK PRIMARY KEY(FLIGHT_PASSENGER_ID),
  FLIGHT_ID NUMBER,
  CONSTRAINT FLIGHT_FK FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID),
  PASSENGER_ID NUMBER,
  CONSTRAINT PASSENGER_FK FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID)
);

CREATE SEQUENCE FLIGHT_PASSENGER_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;