CREATE TABLE PASSENGER (
  ID NUMBER,
  CONSTRAINT PASSENGER_PK PRIMARY KEY(ID),
  LAST_NAME NVARCHAR2(50),
  NATIONALITY NVARCHAR2(50),
  DATE_OF_BIRTH TIMESTAMP,
  PASSPORT_CODE NVARCHAR2(10)
);

CREATE SEQUENCE PASSENGER_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;